apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: infra
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http1
    protocol: HTTP
    port: 80
    hostname: "example.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /example-route
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route-2
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /example-route-2
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: extproc-for-http-route
  namespace: infra
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  extProc:
    extensionRef:
      name: full-extproc
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: extproc-for-http-route-2
  namespace: infra
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route-2
  extProc:
    extensionRef:
      name: default-extproc
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: full-extproc
  namespace: infra
spec:
  type: ExtProc
  extProc:
    grpcService:
      backendRef:
        name: extproc
        port: 9000
      requestTimeout: 300ms
    failOpen: false
    processingMode:
      requestHeaderMode: SKIP
      responseHeaderMode: SKIP
      requestBodyMode: BUFFERED
      responseBodyMode: BUFFERED
      requestTrailerMode: SEND
      responseTrailerMode: SEND
    messageTimeout: 100ms
    maxMessageTimeout: 500ms
    statPrefix: my_extproc
    routeCacheAction: Clear
    metadataOptions:
      forwarding:
        typed:
        - "io.transformation"
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: default-extproc
  namespace: infra
spec:
  type: ExtProc
  extProc:
    grpcService:
      backendRef:
        name: extproc
        port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: infra
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: test
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: extproc
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    appProtocol: kubernetes.io/h2c
  selector:
    app: ext-authz
